using System.Text;
using Microsoft.CodeAnalysis.Text;
using Rubrum.Analyzers.Helpers;
using Rubrum.Authorization.Analyzers.Models;

namespace Rubrum.Authorization.Analyzers.FileBuilders;

public sealed class DefinitionFileBuilder : IDisposable
{
    private readonly StringBuilder _sb;
    private readonly CodeWriter _writer;

    public DefinitionFileBuilder()
    {
        _sb = new StringBuilder();
        _writer = new CodeWriter(_sb);
    }

    public void WriteHeader()
    {
        _writer.WriteIndentedLine("// <auto-generated/>");
        _writer.WriteLine();
        _writer.WriteIndentedLine("#nullable enable");
        _writer.WriteIndentedLine("#pragma warning disable");
        _writer.WriteLine();
        _writer.WriteIndentedLine("using System;");
        _writer.WriteIndentedLine("using Rubrum.Authorization.Permissions;");
        _writer.WriteLine();
    }

    public void WriteBeginNamespace(string ns)
    {
        _writer.WriteIndentedLine("namespace {0}", ns);
        _writer.WriteIndentedLine("{");
        _writer.IncreaseIndent();
    }

    public void WriteBeginClass(string name)
    {
        _writer.WriteIndentedLine("public static partial class {0}", name);
        _writer.WriteIndentedLine("{");
        _writer.IncreaseIndent();
    }

    public void WriteRelationProperty(RelationInfo relation)
    {
        _writer.WriteIndentedLine(
            "public static {0} {1} {{ get; }} = new {0}();",
            relation.ClassName,
            relation.PropertyName);
        _writer.WriteLine();
    }

    public void WritePermissionProperty(PermissionInfo permission)
    {
        _writer.WriteIndentedLine(
            "public static PermissionLink {0} {{ get; }} = new PermissionLink(\"{0}\");",
            permission.PropertyName);
        _writer.WriteLine();
    }

    public void WritePermissionMethod(PermissionInfo permission)
    {
        _writer.WriteIndentedLine("public static partial Permission {0}Configure();", permission.PropertyName);
        _writer.WriteLine();
    }

    public void WriteRelationClass(SourceText sourceText)
    {
        foreach (var line in sourceText.ToString().Split('\n'))
        {
            _writer.WriteIndentedLine(line);
        }
    }

    public void WriteEndClass()
    {
        _writer.DecreaseIndent();
        _writer.WriteIndentedLine("}");
    }

    public void WriteEndNamespace()
    {
        _writer.DecreaseIndent();
        _writer.WriteIndentedLine("}");
        _writer.WriteLine();
    }

    public override string ToString()
        => _sb.ToString();

    public SourceText ToSourceText()
        => SourceText.From(ToString(), Encoding.UTF8);

    public void Dispose()
    {
        _writer.Dispose();
    }
}
