namespace Rubrum.Platform.AdministrationService;

public class AdministrationServiceEntityFrameworkCoreTestBase
    : AdministrationServiceTestBase<AdministrationServiceEntityFrameworkCoreTestModule>;
