name: pipeline

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x.x'

      - name: Install Dapr
        run: |
          wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash
          dapr --version

      - name: Install .NET Aspire workload
        run: dotnet workload install aspire
        working-directory: ./Rubrum.Platform.AppHost/Rubrum.Platform.AppHost.csproj

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: |
          echo "Building project..."
          ls -R Rubrum.Platform.AppHost
          dotnet build --configuration Release --runtime linux-x64 Rubrum.Platform.AppHost/Rubrum.Platform.AppHost.csproj

      - name: Test
        run: dotnet test

      - name: Run Aspire
        run: |
          echo "Running Aspire..."
          cd Rubrum.Platform.AppHost
          ls bin/Release/net8.0/linux-x64/
          dotnet run --project ./Rubrum.Platform.AppHost.csproj --no-restore --no-build -- compose
