name: pipeline

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x.x'

      - name: Install Dapr
        run: |
          wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash
          dapr --version

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.8.0'

      - name: Install Aspire
        run: |
          npm install -g @aspirehq/cli
          aspire version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test
